"""Every package module imports cleanly (no syntax/typing/import-cycle errors)."""

from __future__ import annotations

import importlib

import pytest

MODULES = [
    "plantdx",
    "plantdx.cli",
    "plantdx.__main__",
    "plantdx.audit",
    "plantdx.audit.models",
    "plantdx.audit.discovery",
    "plantdx.audit.images",
    "plantdx.audit.duplicates",
    "plantdx.audit.report",
    "plantdx.audit.engine",
    "plantdx.normalization",
    "plantdx.normalization.models",
    "plantdx.normalization.engine",
    "plantdx.normalization.report",
    "plantdx.core",
    "plantdx.core.enums",
    "plantdx.core.exceptions",
    "plantdx.core.types",
    "plantdx.core.seeding",
    "plantdx.config",
    "plantdx.config.schema",
    "plantdx.config.loader",
    "plantdx.knowledge_base",
    "plantdx.knowledge_base.models",
    "plantdx.knowledge_base.loader",
    "plantdx.ontology",
    "plantdx.ontology.models",
    "plantdx.ontology.builder",
    "plantdx.ontology.concept_schema",
    "plantdx.ontology.domain",
    "plantdx.ontology.domain.models",
    "plantdx.ontology.domain.policies",
    "plantdx.ontology.domain.graph",
    "plantdx.ontology.domain.builder",
    "plantdx.ontology.domain.validator",
    "plantdx.ontology.domain.statistics",
    "plantdx.ontology.domain.serialization",
    "plantdx.ontology.domain.checksum",
    "plantdx.vocabulary",
    "plantdx.vocabulary.models",
    "plantdx.vocabulary.builder",
    "plantdx.vocabulary.lexicon",
    "plantdx.vocabulary.expander",
    "plantdx.vocabulary.domain",
    "plantdx.vocabulary.domain.models",
    "plantdx.vocabulary.domain.policies",
    "plantdx.vocabulary.domain.graph_queries",
    "plantdx.vocabulary.domain.builder",
    "plantdx.vocabulary.domain.lexicon",
    "plantdx.vocabulary.domain.validator",
    "plantdx.vocabulary.domain.statistics",
    "plantdx.vocabulary.domain.serialization",
    "plantdx.vocabulary.domain.checksum",
    "plantdx.concepts",
    "plantdx.concepts.models",
    "plantdx.concepts.policies",
    "plantdx.concepts.builder",
    "plantdx.concepts.validator",
    "plantdx.concepts.statistics",
    "plantdx.concepts.serialization",
    "plantdx.concepts.checksum",
    "plantdx.templates",
    "plantdx.templates.models",
    "plantdx.templates.loader",
    "plantdx.templates.validator",
    "plantdx.templates.statistics",
    "plantdx.templates.serialization",
    "plantdx.templates.checksum",
    "plantdx.corpus",
    "plantdx.corpus.models",
    "plantdx.corpus.seeds",
    "plantdx.corpus.planner",
    "plantdx.corpus.generator",
    "plantdx.corpus.validator",
    "plantdx.corpus.builder",
    "plantdx.corpus.statistics",
    "plantdx.corpus.serialization",
    "plantdx.corpus.checksum",
    "plantdx.exporters",
    "plantdx.exporters.formats",
    "plantdx.generation",
    "plantdx.generation.models",
    "plantdx.generation.selector",
    "plantdx.generation.templates",
    "plantdx.generation.realizer",
    "plantdx.generation.planner",
    "plantdx.generation.engine",
    "plantdx.validation",
    "plantdx.validation.report",
    "plantdx.validation.validators",
    "plantdx.validation.battery",
    "plantdx.validation.grammar",
    "plantdx.diversity",
    "plantdx.diversity.deduplicator",
    "plantdx.diversity.controller",
    "plantdx.diversity.metrics",
    "plantdx.dataset",
    "plantdx.dataset.serialization",
    "plantdx.dataset.emitter",
    "plantdx.dataset.splits",
    "plantdx.dataset.label_map",
    "plantdx.dataset.instructions",
    "plantdx.dataset.converters",
    "plantdx.qa",
    "plantdx.qa.sampling",
    "plantdx.qa.review",
    "plantdx.qa.acceptance",
    "plantdx.training",
    "plantdx.training.qlora",
    "plantdx.training.mlx_runner",
    "plantdx.training.config",
    "plantdx.training.command",
    "plantdx.training.lora",
    "plantdx.training.models",
    "plantdx.training.planner",
    "plantdx.training.scheduler",
    "plantdx.training.seeds",
    "plantdx.training.checkpoints",
    "plantdx.training.metrics",
    "plantdx.training.reports",
    "plantdx.training.runner",
    "plantdx.training.inference",
    "plantdx.training.data",
    "plantdx.training.data.label_map",
    "plantdx.training.data.discovery",
    "plantdx.training.data.instructions",
    "plantdx.training.data.corpus_pool",
    "plantdx.training.data.pairing",
    "plantdx.training.data.splits",
    "plantdx.training.data.builder",
    "plantdx.evaluation",
    "plantdx.evaluation.metrics",
    "plantdx.evaluation.zero_shot",
    "plantdx.evaluation.compare",
    "plantdx.evaluation.config",
    "plantdx.evaluation.integrity",
    "plantdx.evaluation.inference_runner",
    "plantdx.evaluation.text_metrics",
    "plantdx.evaluation.classification",
    "plantdx.evaluation.per_disease",
    "plantdx.evaluation.hallucination",
    "plantdx.evaluation.clinical",
    "plantdx.evaluation.quality",
    "plantdx.evaluation.latency",
    "plantdx.evaluation.stats",
    "plantdx.evaluation.visualize",
    "plantdx.evaluation.samples",
    "plantdx.evaluation.reproducibility",
    "plantdx.evaluation.report",
    "plantdx.evaluation.runner",
    "plantdx.utils",
    "plantdx.utils.hashing",
    "plantdx.utils.io",
    "plantdx.utils.logging",
    "plantdx.utils.versioning",
]


@pytest.mark.unit
@pytest.mark.parametrize("module", MODULES)
def test_module_imports(module: str) -> None:
    assert importlib.import_module(module) is not None


@pytest.mark.unit
def test_version_is_exposed() -> None:
    import plantdx

    assert isinstance(plantdx.__version__, str)
    assert plantdx.__version__.count(".") == 2
